In [2]:
# Section-A :Data Structures & Control Statements
# Create a list of 5 integers
numbers = [10, 20, 30, 40, 50]
print("Original List:", numbers)

# Append
numbers.append(60)
print("After append:", numbers)

# Extend
numbers.extend([70, 80])
print("After extend:", numbers)

# Insert
numbers.insert(2, 25)
print("After insert:", numbers)

# Remove
numbers.remove(40)
print("After remove:", numbers)

# Pop
numbers.pop()
print("After pop:", numbers)

# Index
print("Index of 30:", numbers.index(30))

# Count
print("Count of 20:", numbers.count(20))

# Sort
numbers.sort()
print("After sort:", numbers)

# Reverse
numbers.reverse()
print("After reverse:", numbers)

# Clear
numbers.clear()
print("After clear:", numbers)

Original List: [10, 20, 30, 40, 50]
After append: [10, 20, 30, 40, 50, 60]
After extend: [10, 20, 30, 40, 50, 60, 70, 80]
After insert: [10, 20, 25, 30, 40, 50, 60, 70, 80]
After remove: [10, 20, 25, 30, 50, 60, 70, 80]
After pop: [10, 20, 25, 30, 50, 60, 70]
Index of 30: 3
Count of 20: 1
After sort: [10, 20, 25, 30, 50, 60, 70]
After reverse: [70, 60, 50, 30, 25, 20, 10]
After clear: []


In [3]:
# Create a tuple
students = ("Ravi", "Sita", "Rahul")

print(students)

# Try to change the second name
students[1] = "Priya"

print(students)

('Ravi', 'Sita', 'Rahul')


TypeError: 'tuple' object does not support item assignment

# Explanation 
A tuple is immutable, so we cannot change its elements after it is created. Therefore, Python displays a TypeError.

In [4]:
# Create a set with duplicate values
numbers = {10, 20, 30, 20, 40, 10, 50}
print(numbers)

{50, 20, 40, 10, 30}


# Explanation
A set stores only unique values. It automatically removes duplicate elements. So, 10 and 20 appear only once in the output. Also, sets do not maintain the insertion order, so the elements may be displayed in a different order.

In [6]:
# Create a dictionary
student = {"name": "Ravi", "age": 20, "city": "Kadapa"}

# Update age
student["age"] = 21

# Add email
student["email"] = "ravi@gmail.com"

# Print the dictionary
print(student)

{'name': 'Ravi', 'age': 21, 'city': 'Kadapa', 'email': 'ravi@gmail.com'}


In [7]:
# Check voting eligibility

age = 20

if age >= 18:
    print("Eligible to vote")
else:
    print("Not eligible to vote")

Eligible to vote


In [8]:
# Grade Program

marks = 85

if marks >= 90:
    print("Grade A")
elif marks >= 75:
    print("Grade B")
elif marks >= 50:
    print("Grade C")
else:
    print("Fail")

Grade B


In [9]:
# Check positive, even, zero, or negative

num = 8

if num > 0:
    if num % 2 == 0:
        print("Positive and Even")
    else:
        print("Positive and Odd")
elif num == 0:
    print("Zero")
else:
    print("Negative")

Positive and Even


In [14]:
# Section B: Numpy
import numpy as np

# Scalar
a = np.array(5)
print("Scalar:")
print(a)

# 1D Array
b = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(b)

# 2D Array
c = np.array([[10, 20, 30],
              [40, 50, 60]])
print("2D Array:")
print(c)

Scalar:
5
1D Array:
[1 2 3 4 5]
2D Array:
[[10 20 30]
 [40 50 60]]


In [11]:
import numpy as np

# Generate a 4x4 array with random integers
arr = np.random.randint(0, 101, (4, 4))

print(arr)

[[93 32 12 57]
 [61 99 28 61]
 [37 16  7 80]
 [ 6 99 55  1]]


In [13]:
import numpy as np
import pandas as pd

# Create a 3x3 NumPy array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Convert to DataFrame
df = pd.DataFrame(arr, columns=["A", "B", "C"])

print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


In [18]:
# Section C: Exploring Pandas
import pandas as pd

# Create a DataFrame
data = {
    "Name": ["Ravi", "Sita", "Ram", "Anu", "Kiran", "Ravi", "Priya", "Raj", "Rani", "Ravi"],
    "Age": [20, 21, 22, 23, 24, 20, 25, 26, 27, 20],
    "City": ["Kadapa", "Hyderabad", "Chennai", "Delhi", "Mumbai", "Kadapa", "Pune", "Goa", "Vizag", "Kadapa"],
    "Salary": [25000, 30000, None, 35000, 40000, 25000, 45000, None, 50000, 25000]
}

df = pd.DataFrame(data)

# Display information
print(df.info())

# Display statistics
print(df.describe())

# Select Name and City columns
print(df[["Name", "City"]])

# Drop City column
df = df.drop("City", axis=1)
print(df)

# Fill missing Salary values with mean
df["Salary"] = df["Salary"].fillna(df["Salary"].mean())
print(df)

# Remove duplicate rows
df = df.drop_duplicates()
print(df)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes
None
             Age       Salary
count  10.000000      8.00000
mean   22.800000  34375.00000
std     2.616189   9797.04766
min    20.000000  25000.00000
25%    20.250000  25000.00000
50%    22.500000  32500.00000
75%    24.750000  41250.00000
max    27.000000  50000.00000
    Name       City
0   Ravi     Kadapa
1   Sita  Hyderabad
2    Ram    Chennai
3    Anu      Delhi
4  Kiran     Mumbai
5   Ravi     Kadapa
6  Priya       Pune
7    Raj        Goa
8   Rani      Vizag
9   Ravi     Kadapa
    Name  Age   Salary
0   Ravi   20  25000.0
1   Sita   21  30000.0
2    Ram   22      NaN
3    Anu   23  35000.0
